/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f1xx.h"

#include "Usart1.h"

#include <tim2.h>

#include "dht11.h"

#include <I2C.h>

#include "Oled.h"

int main(void)
{

	uint8_t HumidadeI = 0, HumidadeD = 0, TemperaturaI = 0, TemperaturaD = 0;

	RCC_setup();

	USART1_setup();
	uart_write("usart set\n\r");

	TIM2_setup();
	uart_write("tim2 set\n\r");

	dht11_setup();
	uart_write("dht11 set\n\r");

    I2C1_setup();
    uart_write("I2C set\n\r");

    OLED_init();
    uart_write("I2C init\n\r");

    OLED_send_command(0xAF); // Comando para ligar o OLED (Display ON)

    Oled_intro();


	while(1)
	{
		TIM2_delay_ms(1000);
		//GPIOC->ODR ^= (1 << 13);
		if(dht11_ping()){


			TemperaturaI = dht11_read();
			TemperaturaD = dht11_read();

			HumidadeI = dht11_read();
			HumidadeD = dht11_read();

			uart_info_dht11(TemperaturaI,TemperaturaD,HumidadeI,HumidadeD);

			OLED_info_dht11(TemperaturaI,TemperaturaD,HumidadeI,HumidadeD);

		}


	}
}









